"""
stats_active_days_alpha05.py
───────────────────────────────────────────────────────────────────────────────
Runs hypothesis tests at a pre-specified significance level (alpha = 0.05)
and prints explicit reject / fail-to-reject decisions alongside all test
statistics required for a CHI paper methods section.

This script is a self-contained decision layer on top of the analyses in
``significance_test.py``.  It is intended to produce the binary significance
decision in a way that is easy to audit: alpha is declared at the top of the
file and every decision string is generated by a single function so the
threshold is applied consistently across all tests.

Statistical approach
--------------------
Two complementary tests are run (see ``significance_test.py`` for rationale):

  1. Welch two-sample t-test (parametric, unequal-variance correction)
  2. Mann–Whitney U test, two-sided (non-parametric)

Alpha
-----
alpha = 0.05  →  95% confidence level
H0: the two groups have the same population location parameter.
H1: the location parameters differ (two-sided).

Usage
-----
    python stats_active_days_alpha05.py

Edit the ``counter`` and ``journal`` arrays in ``main()`` to match your data.

Reproducibility note
--------------------
No randomness; all statistics are deterministic.

Requirements
------------
    python  >= 3.9
    numpy   >= 1.21
    scipy   >= 1.7   (exact Mann–Whitney requires scipy >= 1.7)
───────────────────────────────────────────────────────────────────────────────
"""

from __future__ import annotations

import math
import numpy as np

try:
    from scipy import stats
except ImportError as e:
    raise SystemExit(
        "This script needs scipy. Install it with: pip install scipy"
    ) from e


# ── Configuration ─────────────────────────────────────────────────────────────

ALPHA = 0.05   # Pre-registered significance level; change here to update all decisions


# ── Statistical helpers ───────────────────────────────────────────────────────

def welch_df(s1: float, n1: int, s2: float, n2: int) -> float:
    """
    Welch–Satterthwaite effective degrees of freedom.

    Corrects for unequal variances and sample sizes in the two-sample t-test.
    Formula follows Welch (1947).

    Parameters
    ----------
    s1, s2 : float   Sample standard deviations.
    n1, n2 : int     Sample sizes.

    Returns
    -------
    float   Effective df (may be non-integer).
    """
    v1  = (s1**2) / n1
    v2  = (s2**2) / n2
    num = (v1 + v2) ** 2
    den = (v1**2) / (n1 - 1) + (v2**2) / (n2 - 1)
    return num / den


def mean_diff_ci(
    m1: float, s1: float, n1: int,
    m2: float, s2: float, n2: int,
    alpha: float,
) -> tuple[float, float]:
    """
    Compute the (1 − alpha) confidence interval for the mean difference m1 − m2.

    Uses Welch–Satterthwaite df so the interval is valid under unequal
    variances. The alpha argument is taken from the module-level constant
    to ensure the CI matches the declared significance level.

    Parameters
    ----------
    m1, m2 : float    Group means.
    s1, s2 : float    Sample standard deviations.
    n1, n2 : int      Sample sizes.
    alpha  : float    Significance level (typically the module constant ALPHA).

    Returns
    -------
    (float, float)   Lower and upper bounds.
    """
    diff  = m1 - m2
    se    = math.sqrt((s1**2) / n1 + (s2**2) / n2)
    df    = welch_df(s1, n1, s2, n2)
    tcrit = stats.t.ppf(1 - alpha / 2, df)
    return diff - tcrit * se, diff + tcrit * se


def decision(p: float, alpha: float = ALPHA) -> str:
    """
    Return a plain-language significance decision string.

    Centralising this logic ensures the same threshold (ALPHA) is applied
    identically to every test, reducing the risk of copy-paste errors when
    reporting multiple comparisons.

    Parameters
    ----------
    p     : float   Observed p-value.
    alpha : float   Significance level (default: module constant ALPHA).

    Returns
    -------
    str
        "REJECT H0 (significant)" if p < alpha, else
        "FAIL TO REJECT H0 (not significant)".
    """
    return (
        "REJECT H0 (significant)"
        if p < alpha
        else "FAIL TO REJECT H0 (not significant)"
    )


# ── Main routine ──────────────────────────────────────────────────────────────

def main() -> None:
    """
    Print hypothesis-test results with explicit alpha-level decisions.

    Steps
    -----
    1. Declare alpha and print group-level descriptives.
    2. Run Welch t-test; print t, df, p, decision, mean difference, and CI.
    3. Run Mann–Whitney U test; print U, p, and decision.

    Data entry
    ----------
    Replace the ``counter`` and ``journal`` arrays below with the active-day
    counts from your study.  One value per participant; order does not matter.
    """
    # ── Data — replace with values from your study ────────────────────────────
    counter = np.array([7, 6, 7, 6, 6, 7, 6, 7, 3, 5], dtype=float)
    journal = np.array([4, 3, 3, 1, 6, 2, 4, 4],       dtype=float)

    # ── Shared descriptives ───────────────────────────────────────────────────
    m1, m2 = float(counter.mean()), float(journal.mean())
    s1, s2 = float(counter.std(ddof=1)), float(journal.std(ddof=1))   # sample SD
    n1, n2 = counter.size, journal.size

    print(f"Alpha (significance level) = {ALPHA:.2f}  "
          f"→ confidence level = {1 - ALPHA:.2f}\n")
    print(f"Counter: n={n1}, mean={m1:.2f}, sd={s1:.2f}")
    print(f"Journal: n={n2}, mean={m2:.2f}, sd={s2:.2f}\n")

    # ── Welch two-sample t-test ───────────────────────────────────────────────
    t_res        = stats.ttest_ind(counter, journal, equal_var=False)
    df           = welch_df(s1, n1, s2, n2)
    diff         = m1 - m2
    ci_lo, ci_hi = mean_diff_ci(m1, s1, n1, m2, s2, n2, alpha=ALPHA)

    print("Welch two-sample t-test")
    print(
        f"t({df:.2f}) = {t_res.statistic:.2f}, "
        f"p = {t_res.pvalue:.4f} → {decision(t_res.pvalue)}"
    )
    print(f"Mean difference (Counter − Journal) = {diff:.2f} days")
    print(
        f"{int((1 - ALPHA) * 100)}% CI for mean difference = "
        f"[{ci_lo:.2f}, {ci_hi:.2f}]\n"
    )

    # ── Mann–Whitney U test ───────────────────────────────────────────────────
    # Two-sided: H1 is that the distributions differ in location.
    # Exact enumeration requested (scipy >= 1.7); asymptotic fallback for older installs.
    try:
        mw = stats.mannwhitneyu(counter, journal,
                                 alternative="two-sided", method="exact")
    except TypeError:
        mw = stats.mannwhitneyu(counter, journal, alternative="two-sided")

    print("Mann–Whitney U test (two-sided)")
    print(
        f"U = {mw.statistic:.0f}, "
        f"p = {mw.pvalue:.4f} → {decision(mw.pvalue)}"
    )


if __name__ == "__main__":
    main()
